-- ============================================================================
-- CATEGORY_INTELLIGENCE_VIEW — Baby Mart Category Intelligence Semantic View
-- Database: BABY_MART_DEMO.ANALYTICS
-- ============================================================================

CREATE OR REPLACE SEMANTIC VIEW BABY_MART_DEMO.ANALYTICS.CATEGORY_INTELLIGENCE_VIEW
  TABLES (
    CLV AS BABY_MART_DEMO.ANALYTICS.DT_CLV_BY_BRAND,
    COMPETITIVE AS BABY_MART_DEMO.ANALYTICS.DT_COMPETITIVE_POSITION,
    DIFOT AS BABY_MART_DEMO.ANALYTICS.DT_SUPPLIER_DIFOT,
    PROMOTIONS AS BABY_MART_DEMO.ANALYTICS.DT_PROMOTIONAL_EFFECTIVENESS,
    SEGMENTS AS BABY_MART_DEMO.ANALYTICS.DT_CUSTOMER_SEGMENT_PERFORMANCE,
    SELLTHROUGH AS BABY_MART_DEMO.ANALYTICS.DT_SELLTHROUGH_WEEKLY,
    SWITCHING AS BABY_MART_DEMO.ANALYTICS.DT_BRAND_SWITCHING
  )
  DIMENSIONS (
    CLV.BRAND_NAME AS BRAND_NAME COMMENT='Brand name',
    CLV.CATEGORY AS CATEGORY COMMENT='Product category',

    COMPETITIVE.BRAND_NAME AS BRAND_NAME COMMENT='Brand name',
    COMPETITIVE.CATEGORY AS CATEGORY COMMENT='Product category',
    COMPETITIVE.COMPETITOR_NAME AS COMPETITOR_NAME COMMENT='Competitor (Coles, Woolworths, Amazon AU, Chemist Warehouse)',
    COMPETITIVE.FISCAL_WEEK AS FISCAL_WEEK COMMENT='Fiscal week',
    COMPETITIVE.FISCAL_YEAR AS FISCAL_YEAR COMMENT='Fiscal year',

    DIFOT.BRAND_NAME AS BRAND_NAME COMMENT='Brand name',
    DIFOT.CATEGORY AS CATEGORY COMMENT='Product category',
    DIFOT.FISCAL_WEEK AS FISCAL_WEEK COMMENT='Fiscal week',
    DIFOT.FISCAL_YEAR AS FISCAL_YEAR COMMENT='Fiscal year',

    PROMOTIONS.BRAND_NAME AS BRAND_NAME COMMENT='Brand name',
    PROMOTIONS.CATEGORY AS CATEGORY COMMENT='Product category',
    PROMOTIONS.MECHANIC AS MECHANIC COMMENT='Promotion mechanic (% Off, Bundle, GWP, BOGO, Multi-buy)',

    SEGMENTS.BRAND_NAME AS BRAND_NAME COMMENT='Brand name',
    SEGMENTS.FISCAL_YEAR AS FISCAL_YEAR COMMENT='Fiscal year',
    SEGMENTS.SEGMENT_NAME AS SEGMENT_NAME COMMENT='Customer segment (First-time Parents, Second-time Parents, Gift Buyers, Grandparents, Expecting, Registry Shoppers)',
    SEGMENTS.SUPPLIER_NAME AS SUPPLIER_NAME COMMENT='Supplier name',

    SELLTHROUGH.BRAND_NAME AS BRAND_NAME COMMENT='Product brand name',
    SELLTHROUGH.CATEGORY AS CATEGORY COMMENT='Product category (Prams & Strollers, Car Seats, Nappies & Wipes, Clothing, Feeding)',
    SELLTHROUGH.CLASS AS CLASS COMMENT='Product sub-category',
    SELLTHROUGH.FISCAL_WEEK AS FISCAL_WEEK COMMENT='Fiscal week number',
    SELLTHROUGH.FISCAL_YEAR AS FISCAL_YEAR COMMENT='Fiscal year (July-June)',
    SELLTHROUGH.REGION AS REGION COMMENT='Region type (Metro, Regional, CBD)',
    SELLTHROUGH.STATE AS STATE COMMENT='Australian state (VIC, NSW, QLD, SA, WA, TAS, ACT, NT)',
    SELLTHROUGH.STORE_NAME AS STORE_NAME COMMENT='Store name',
    SELLTHROUGH.SUPPLIER_NAME AS SUPPLIER_NAME COMMENT='Supplier company name',

    SWITCHING.CATEGORY AS CATEGORY COMMENT='Product category',
    SWITCHING.CLASS AS CLASS COMMENT='Product class',
    SWITCHING.FROM_BRAND AS FROM_BRAND COMMENT='Brand customers switched from',
    SWITCHING.TO_BRAND AS TO_BRAND COMMENT='Brand customers switched to'
  )
  AI_VERIFIED_QUERIES (
    'Which brands are losing the most customers in Nappies & Wipes?' AS (
      QUESTION 'Which brands are losing the most customers in Nappies & Wipes?'
      VERIFIED_BY 'Jarry Chen'
      SQL 'SELECT FROM_BRAND, TO_BRAND, SUM(SWITCH_COUNT) AS customers_switched FROM BABY_MART_DEMO.ANALYTICS.VW_SUPPLIER_SWITCHING WHERE CATEGORY ILIKE ''Nappies & Wipes'' GROUP BY FROM_BRAND, TO_BRAND ORDER BY customers_switched DESC NULLS LAST;'
    )
  );
