-- ============================================================================
-- 00_framework_tables.sql  (SPLIT INTO MODULES - see modules/ and modules.yaml)
--
-- This monolith has been replaced by the modular installer. The framework is
-- now organized into six selectable capability modules under modules/:
--
--   modules/core/sql/         schema + observability views      (always)
--   modules/evaluation/sql/   eval tables + accuracy view
--   modules/monitoring/sql/   monitoring tables + trend/quality views
--   modules/alerts/sql/       Snowflake alerts
--   modules/automation/sql/   scheduled tasks
--
-- Install a subset (dependencies resolved automatically):
--
--   python setup/install.py --modules monitoring,dashboard      # dashboard + data
--   python setup/install.py --modules all                       # everything
--   python setup/install.py --list                              # show modules
--
-- The installer performs the {{FRAMEWORK_DB}} / {{FRAMEWORK_SCHEMA}} /
-- {{WAREHOUSE}} substitution and executes each module's SQL. See
-- docs/how-to/choose-modules.md and .cortex/skills/agentops-configure.
-- ============================================================================
